# Generated by Django 5.2.4 on 2025-08-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_orderitem_options_rename_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['placed_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Shipped'), ('T', 'In Transit'), ('D', 'Out for Delivery'), ('C', 'Complete'), ('F', 'Failed'), ('X', 'Cancelled')], default='P', max_length=1),
        ),
    ]
